package za.ac.nwu.Project1.Database.queries;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import za.ac.nwu.Project1.Database.entities.Account;

import javax.transaction.Transactional;

@Repository
public interface AccountRepository extends CrudRepository<Account, Long> {
    @Modifying
    @Transactional
    @Query(value = "INSERT INTO Account(Account_ID, Discovery_Miles) VALUES(?1, ?2)", nativeQuery = true)
    void insertAccount(Long id, Long miles);                        //id autogenerated, will it work? Add bridge table to link IDs of all tables

    @Transactional
    @Query("SELECT Miles FROM Account a WHERE a.Account_ID = ?1")
    Account findMilesById(Long id);                             //? void findMilesById(Long id)

    @Transactional
    @Query(value = "UPDATE Account(Discovery_Miles) a VALUES(?2) WHERE a.Account_ID = ?1")
    void updateMiles(Long id, Long miles);

    @Transactional
    @Query
    void deleteAccount(Long id, Long miles);





}
