package za.ac.nwu.Project1.Database.queries;

import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import za.ac.nwu.Project1.Database.entities.Account;
import javax.transaction.Transactional;

@Repository
public interface AccountRepository extends CrudRepository<Account, Long> {
    @Modifying
    @Transactional
    @Query(value = "INSERT INTO Account(AccountID, DiscoveryMiles) VALUES(?1, ?2)", nativeQuery = true)
    void insertAccount(Long id, Long miles);                        //id autogenerated, will it work? Add bridge table to link IDs of all tables

    @Transactional
    @Query(value = "SELECT Miles FROM Account a WHERE a.AccountID = ?1", nativeQuery = true)
    void findMilesById(Long id);                             //? void findMilesById(Long id)

    @Modifying
    @Transactional
    @Query(value = "UPDATE Account SET DiscoveryMiles = (?2) WHERE AccountID = ?1", nativeQuery = true)
    void updateMiles(Long id, Long miles);

    @Modifying
    @Transactional
    @Query(value = "DELETE FROM Account WHERE AccountID = ?1", nativeQuery = true)
    void deleteAccount(Long id);





}
